export enum Screens {
  BOTTOM = "BOTTOM",

  //Main
  HOME = "HOME",
  SEARCH = "SEARCH",
  REELS = "REELS",
  PROFILE = "PROFILE",
  NOTIFICATION = "NOTIFICATION",

  //Auth
  AUTH = "AUTH",
  REGISTRATION = "REGISTRATION",
}
